### ISSUE TITLE
Interoperability identifiers in coverage datasets?

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-102-Product-Specification#109]
See https://github.com/iho-ohi/98-interoperability/issues/54 for a new question about the use or non-use of interoperability identifiers in coverage datasets.

**Comment by hasel001** [comment]
Per Julia, there is no current need for S-102 to have the interoperability identifier. I am marking this issue closed, but it is understood that future circumstances (as in all cases) might merit reintroduction of the topic.
