### ISSUE TITLE
Unused 'GFM' abbreviated term

### ISSUE THREAD

**Issue by giumas** [iho-ohi/S-102-Product-Specification#113]
In PS 2.3.3, 'GFM' is listed as an abbreviated term for 'General Feature Model':

![msedge_qKeD8Z7xIs](https://github.com/iho-ohi/S-102-Product-Specification/assets/2849257/b2f8a356-2df2-492e-80e8-0ff838bdd8ba)

It does not seem that 'GFM' is used in the PS (maybe in figures?). 
There are 2 cases where 'General Feature Model' is used in place of 'GFM'.

The suggestion is to remove 'GFM' from PS 2.3.3 or, alternatively, to use the abbreviated term in place of  'General Feature Model'.

**Comment by giumas** [comment]
The issue is also mentioned in https://github.com/iho-ohi/S-102-Product-Specification/issues/115

**Comment by hasel001** [comment]
Addressed [here](https://github.com/iho-ohi/S-102-Product-Specification/commit/02046e62c84a9acfe792d96d152b2cac5e4b3903). Thank you for the review!
