### ISSUE TITLE
Missing 'DCEG' as an abbreviated term

### ISSUE THREAD

**Issue by giumas** [iho-ohi/S-102-Product-Specification#114]
In PS 2.3.3, 'DCEG' is not listed. 

However, the acronym is defined twice in the PS:

- PS 2.4: _The Data Classification and Encoding Guide (**DCEG**) provides guidance on how data product content must be captured._ 
- PS 8:  _The Data Classification and Encoding Guide (**DCEG**) describes how data describing the real world should be captured using the types defined in the S-102 Feature Catalogue._

The proposed solution is to add DCEG to 2.3.3 and then just use the acronym in the 2 listed places, or a alternatively, removing the DCEG acronym from the 2 listed places in the PS.

**Comment by hasel001** [comment]
Addressed [here](https://github.com/iho-ohi/S-102-Product-Specification/commit/2871e416af35c538544722599d6780fd4c1d0618), [here](https://github.com/iho-ohi/S-102-Product-Specification/commit/4b26f5e3ba8f20b24ab2893c5b4820c9911a21cb), and [here](https://github.com/iho-ohi/S-102-Product-Specification/commit/9376d3d42ef7aafdcd846cd5e23c0e965ef96926). Thank you for your review!
