### ISSUE TITLE
bathyCoverage misleading description

### ISSUE THREAD

**Issue by giumas** [iho-ohi/S-102-Product-Specification#118]
The current description of `bathyCoverage` from table 11 is:

> Flag for grid cells populated by interpolation.

This formulation is misleading because it makes the PS reader think that the `bathyCoverage` flag should be true in case that the grid cell is interpolated.

The paired note clarifies a bit, but it is not enough to remove confusion (and it still uses the old name of `fullCoverage`):

> The attribute bathyCoverage is especially useful in side-scan surveys which are characterized by gaps in bathymetric observations with full coverage side-scan imagery. In this case, interpolated gaps between bathymetry coverage would show fullCoverage = True and bathyCoverage = False. However, if fullCoverage = False, bathyCoverage must also equal False (e.g., gaps between single beam echosounder data without correlating side-scan sonar coverage).

This note translates to:

| Depth type                                     | fullCoverage | bathyCoverage |
| ------------------------------------- | -------------- | ----------------- |
| Measured depth                             | True               | True                  |
| Interpolated, insonified (e.g., SSS)  | True               | False                 |
| Interpolated, not insonified            | False              | False                 |
| NOT ALLOWED                               | False              | True                  |

A minimal change to fix the misleading description would be to change the description to be:

> **False** for grid cells populated by interpolation.

Although this ticket is related to https://github.com/iho-ohi/S-102-Product-Specification/issues/80, it aims to provide a working solution for PS 3.0.0.

**Comment by anthonyklemm** [comment]
Yes, this makes sense. Thank you @giumas. We also find the current language confusing and believe your suggested minimal change helps clear up the confusion.

**Comment by hasel001** [comment]
Changes implemented [here](https://github.com/iho-ohi/S-102-Product-Specification/commit/bf13786b7aed0a0f60376ede0e9e161d537ad4d2) and [here](https://github.com/iho-ohi/S-102-Product-Specification/commit/97f79b1aee14415251e45a1ad5680286185a9d83). Thank you for raising the issue!

**Comment by RohdeBSH** [comment]
`bathyCoverage` & `bathymetricUncertaintyType` will not work.
These attributes have not been registered in the IHO GI Registry.
However, they must be registered according to S-100 5.2.0 clause 10c-9.6.2.

@anthonyklemm can you have a look please.

**Comment by giumas** [comment]
@RohdeBSH, I believe that there is already a ticket about bathyCoverage: https://github.com/iho-ohi/S-102-Product-Specification/issues/80 
This ticket was specific to the misleading description.

**Comment by RohdeBSH** [comment]
Thanks for the tip, I hadn't remembered that.
Nevertheless, as long as it is not registered, you can change it as you wish. Unfortunately, unregistered attributes must be removed, otherwise the whole S-102 3.0.0 would become invalid.
The registration process takes at least 60 days. If the attributes were not submitted in May, it will be impossible to approve them by 19.07.2024.
This also applies to the "id" of the QualityOfBathymetryCoverage.
This is a very serious problem and cannot be mentioned often enough.

**Comment by giumas** [comment]
The discussion will continue in https://github.com/iho-ohi/S-102-Product-Specification/issues/115
