### ISSUE TITLE
Update exchange catalog and external metadata for S-100 5.0.0

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-102-Product-Specification#12]
The clauses describing external metadata and the exchange catalog are to be updated for compatibility with S-100 5.0.0.  As discussed during the 18 January teleconference the plan is for me to make the updates to a Word file and send it to Lawrence for application to the 2.2.0 Metanorma files.

**Comment by rmalyankar** [comment]
Updated figures for clause 12, assuming ISO metadata files are retained

![Fig 12-X2 Components of the exchange set](https://user-images.githubusercontent.com/51188078/215617781-c73fab4f-17ed-49b5-a473-ff76aba4c7cb.png)

![Fig 12-X3 Relationship between exchange catalogue and metadata](https://user-images.githubusercontent.com/51188078/215617829-b2cfaf43-1ada-4042-90d5-ab6f26bbe2cf.png)

![Fig 12-X4 Details of exchange set catalogue classes](https://user-images.githubusercontent.com/51188078/215617852-ff2a6124-8abe-4bc5-9196-87346bfb1625.png)

**Comment by RohdeBSH** [comment]
Hi @rmalyankar ,
are you still working on the Word file or is it just to update the images in the ASCII doc files?

**Comment by hasel001** [comment]
Action pending based on Issue 14 (ISO Metadata files) at this meeting. (lhh, PT12, 13Feb2023)

**Comment by rmalyankar** [comment]
Figures for clause 12, updated according to decisions at PT12 about ISO metadata and support files.

Components for the S-102 exchange set
![S-102 Fig 12-X2 Components of the exchange set](https://user-images.githubusercontent.com/51188078/220578940-1ea4417d-9559-4a52-9d18-f9a3b93c2e25.png)

Relationship between exchange catalogue, discovery metadata and dataset
![S-102 Fig 12-X3 Relationship between exchange catalogue and metadata](https://user-images.githubusercontent.com/51188078/220578982-c4dd5113-6645-4dba-9334-0b450eed4aa1.png)

S-102 Exchange set class details
![S-102 Fig 12-X4 Details of exchange set catalogue classes](https://user-images.githubusercontent.com/51188078/220579045-02a1f442-2334-479a-b3d1-0a808d66392d.png)

**Comment by hasel001** [comment]
We discussed this item during PT13 and determined the issue can be closed.
