### ISSUE TITLE
colorProfile.xml: LITGN is red?

### ISSUE THREAD

**Issue by texnokrates** [iho-ohi/S-102-Product-Specification#126]
I do not know from where it came (probably just copypasta / omission), and perhaps it has currently no impact, but this does not seem right:
```
$ diff S-101_Portrayal-Catalogue-1.5.0/PortrayalCatalog/ColorProfiles/colorProfile.xml S-102-Portrayal-Catalogue-main/PortrayalCatalog/ColorProfiles/colorProfile.xml 
49,50c49,50
<         <color token="LITGN" name="green">
<             <description>Light green</description>
---
>         <color token="LITGN" name="red">
>             <description>Light red</description>
3026c3026
< </cp:colorProfile>
\ Ei rivinvaihtoa tiedoston lopussa
---
>   </cp:colorProfile>
\ Ei rivinvaihtoa tiedoston lopussa
```

**Comment by RohdeBSH** [comment]
In general, this is a PortrayalCatologue issue. @hasel001 , please move the request to the repository for the PortrayalCatalogue.
Thank you

**Comment by texnokrates** [comment]
Oh, I did not notice there is another repository for the portrayal catalogue. Nevermind, I can create a pull request there.
