### ISSUE TITLE
Validation Checks - Request for Feedback - 30 October

### ISSUE THREAD

**Issue by hasel001** [iho-ohi/S-102-Product-Specification#127]
@LizHahessy @rmalyankar have requested our feedback on the draft of S-158:102 0.1.0 posted [here](https://github.com/iho-ohi/S-100-Validation-Checks/tree/main/Documents/S-158-102/0.1.0).

Due to the short time between now and S-100 WG 9, please send any feedback to me (or respond within this issue) by 30 October if possible. Thank you, and I hope to see you all soon in Genoa!

**Comment by RohdeBSH** [comment]
First of all... Good work, thank you very much.

#### Comments
- Comments are included in the attached documents.
  -  [S-158_102 BATHY Validation_Checks_0_1_0_20241015_BSH.docx](https://github.com/user-attachments/files/17517936/S-158_102.BATHY.Validation_Checks_0_1_0_20241015_BSH.docx)
  - [S-158_102_0_1_0_20241015_BSH.xlsx](https://github.com/user-attachments/files/17517938/S-158_102_0_1_0_20241015_BSH.xlsx)
- Excel is not the best format for commenting. You should change the documents to Metanorma format.
- Many tests are not S-102 specific, but general tests for S-100 and HDF5 format. Perhaps something can be outsourced.
- I was missing tests for the enumerations. Unfortunately, it is not enough to test whether the attribute value corresponds to a value of the enumeration. It must also be tested whether the enumeration is completely mapped.

**Comment by tfilppula** [comment]
I'll second what Daniel said above: good work and thank you!

Few comments highlighted in the excel sheet: [S-158_102_0_1_0_20241015_Traficom.xlsx](https://github.com/user-attachments/files/17576611/S-158_102_0_1_0_20241015_Traficom.xlsx)
