### ISSUE TITLE
Product-specific attributes in exchange catalogue

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-102-Product-Specification#16]
Whether S-102 external metadata in CATALOG.XML should include product-specific attributes (such as _griddingMethod_). I recommend:
1. removing all product-specific attributes and classes from the exchange catalogue;
2. determining what product-specific metadata (_griddingMethod_ attribute, structural and acquisition metadata, etc.) is essential to the **navigation** incarnation of S-102.
3. adding any such "must-have" product-specific metadata as embedded metadata in the HDF5 file, for example, adding _griddingMethod_ (assuming it is essential) to the root group attributes.

**Comment by hasel001** [comment]
PT have accepted (1) and have yet to make any decision about (2) and (3). (lhh, PT12, 13Feb2023)

**Comment by skjeves** [comment]
griddingMethod is part of S102_DatasetDiscoveryMetadata in S-102. It was determined to be essential enough for inclusion here + in an additional Annex (Annex F which was now recently removed). Without being an expert on the provision and use of griddingMethod information, I believe at least previously in the project team it was considered to be important information, and thus a good candidate for inclusion in the embedded metadata.

**Comment by hasel001** [comment]
Lawrence is taking action on (a), while (b) may not apply here. Due date for reporting back to the PT is 2 July 2023.

**Comment by hasel001** [comment]
I have removed gridding method and references to it.

* [Removed reference to table from Portrayal clause](https://github.com/iho-ohi/S-102-Product-Specification/pull/40/commits/1f47ae351be0de29a1a9a75e94497ef19eee6d95) 
* [Removed GM row from Root Group Attributes table and removed GM table](https://github.com/iho-ohi/S-102-Product-Specification/pull/40/commits/6b97a1c046e6abddd224086c1dd5ebcdb2c29ea4) 
* [Added 2.3.0 to change log](https://github.com/iho-ohi/S-102-Product-Specification/pull/40/commits/5f94b3fd99134585534a52ced53290ea7c146147)
* [Revised latest change log entry text, cleaned up comment](https://github.com/iho-ohi/S-102-Product-Specification/pull/40/commits/f483a3700222e11061c7ac90f7483942d5a62cef)
* [Fixed misplacement of end of table](https://github.com/iho-ohi/S-102-Product-Specification/pull/40/commits/a3945e7a44ccd36e06ae4f81a282d67cedcbf369)

I think these changes satisfy this issue, but any review and comments would be most appreciated.

**Comment by hasel001** [comment]
Per decision in PT16, this issue appears to be satisfied.
