### ISSUE TITLE
Sharper figure for clause 10.2

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-102-Product-Specification#17]
Figure 8 — Outline of the generic data file structure

<img width="503" alt="Fig_8 (V5 0 Fig 10c-7 Basic structure of S-100 HDF5 file)" src="https://user-images.githubusercontent.com/51188078/215618256-fbed3916-3b4c-4580-899d-de8cae3e44a0.png">

**Comment by RohdeBSH** [comment]
Image was added and should updated in the document automaticaly by metanorma
