### ISSUE TITLE
Need a Tutorial for PT Members

### ISSUE THREAD

**Issue by hasel001** [iho-ohi/S-102-Product-Specification#27]
Discussions during S-102PT12 called for the creation of a GitHub tutorial. With help from @RohdeBSH and @giumas among several others, I added [this page](https://github.com/iho-ohi/S-102-Product-Specification/wiki/S-102-PT-GitHub-Basic-Tutorial) to the repo wiki.

This issue serves as a central point for comments, questions, and suggestions to improve the tutorial. All ideas are welcome and encouraged.

**Comment by rmalyankar** [comment]
Is it possible to add an explanation/confirmation of how to generate documents in a fork of the repository? 

The idea is to generate documents from updated sources for 2.3.0, without affecting anything in the common "iho-ohi/S-102-Product-Specification" repository, until I am ready to create a pull request to merge my updates with 2.3.0 in the Developing branch of the common S-102 repository.

It might be as simple as enabling and applying the same workflow in the forked repository, but before I do that I thought I'd check if there are any dependencies or prerequisites in the workflow, or if it needs customization.

Or are all updates required to be made in a new branch of the common repository (created from the Developing branch so it has the 2.3.0 sources)?

**Comment by hasel001** [comment]
Satisfied per discussion in PT16.
