### ISSUE TITLE
Add figure : Bounding box S-102 

### ISSUE THREAD

**Issue by JLeDeunf** [iho-ohi/S-102-Product-Specification#29]
I am raising an issue, of a French development team, for clarification regarding the boudingbox and in particular the setting of the eastBoundLongitude and northBoundLatitude values. 
Since version 2.1.0 it is not specified exactly how these two values can be calculated, so their implementations can be quite free as long as the unit tests associated with the standard are not in place.
We therefore propose to add a figure to clarify the geometry of the boudingbox with regard to the meshed product, a picture says more than a thousand words.

![boundingbox_S102](https://user-images.githubusercontent.com/125272118/225562260-7d86fa19-9b36-401b-836e-79e02ea317d9.PNG)

This figure is only a first draft and could be improved by indicating for example the numPointsLongitude or other attributes.

**Comment by giumas** [comment]
I support that the addition of a figure like this because it reduces the space for confusion and misunderstandings.

**Comment by RohdeBSH** [comment]
Hello,

unfortunately, it's not quite as simple as it's outlined here. But we need some time to prepare, so please stay tuned! 
We think an explanatory graphic is a good idea.

**Comment by tfilppula** [comment]
Hello everyone,

I would like to second what @RohdeBSH brought up about defining the bounding box by using grid center nodes. To me it would make much more sense to use the grid cell (outer-) boundaries, otherwise we will end up indicating gaps in between neighboring S-102 products.

As pictures tell more than a thousand words, I also put up a couple of images trying to clarify this issue:
Case 1, Bboxes based on grid cell nodes:
![image](https://user-images.githubusercontent.com/13709365/230093043-b072e4c4-ae3b-4007-9f15-295eb7818e9e.png)

Case 2, Bboxes based on grid cell boundaries:
![image](https://user-images.githubusercontent.com/13709365/230093449-b11a70dd-46fe-46a4-8d46-3c5d2aaff4c2.png)

Considering each cell as areas instead of points would also be in line with S-98 safety contour representation.

**Comment by tfilppula** [comment]
Should we also clarify how the bounding box is defined? What I mean is that there are different approaches to this question, cell center nodes vs. cell boundaries is discussed above, but there is also the question of do we take No Data / Fill Value cells into account or not?

In the image below there are 4 different approaches to this question:
1. Using grid cell boundaries, taking No Data cells into account (I think this makes most sense)
2. Using grid cell boundaries, only taking cells with depth information into account
3. Using grid cell nodes, taking No Data cells into account
4. Using grid cell nodes, only taking cells with depth information into account

![image](https://user-images.githubusercontent.com/13709365/230115296-d3fe4197-8c11-4684-ae97-6d5e86669bb9.png)

**Comment by RohdeBSH** [comment]
Very well elaborated.
We prefer the first suggestion as well.

**Comment by poseiron01** [comment]
Yes, very nice Topi! We would also prefer Case 2 where the Bbox is based on grid cell boundaries and the first approach above taking the NoData cells into account. As we mentioned in Monaco we also support the use of Cell area instead of Node. As Topi mentions this is in line with S-98 and how saftey contours are represented(Annex C C-4-1.2).

**Comment by JLeDeunf** [comment]
Hi, thanks @tfilppula and @RohdeBSH for your input! We also prefer Case 2 where the Bbox is based on grid cell boundaries and the first approach above taking the NoData cells into account.

**Comment by hasel001** [comment]
To support this agenda item for this week's S-102PT13 meeting, [this paper](https://iho.int/uploads/user/Services%20and%20Standards/S-100WG/S-102PT/S-102PT13/S102PT13-1.2_2023_EN_Change_Proposal_Grid%20cell%20boundaries%20and%20cell%20areas.pdf) has been uploaded to the official IHO meeting page.

**Comment by tfilppula** [comment]
I add this image to the issue as it's included in the proposition paper and might help clarifying the underlying issue.
![image](https://github.com/iho-ohi/S-102-Product-Specification/assets/13709365/3a9fbd3d-c506-4863-99f4-7cbfadd1018f)

**Comment by hasel001** [comment]
We discussed this issue during PT13. The Project Team agrees that the topic merits further investigation. SMA (@AnnaWall01 , @poseiron01) will take the lead on investigating this issue with the intent of showing their findings and any related proposals during PT14. It is highly encouraged for all contributors to share relevant information as part of this GitHub Issue. Thank you all for your contributions!

**Comment by giumas** [comment]
During PT13, we asked whether all the 4 approaches depicted by @tfilppula are valid based on current PS.

**Comment by AnnaWall01** [comment]
Hi everyone, 
To continue the work Sweden presented at the last PT meeting, we have, together with Finland, further investigated the impacts of the proposal. For better understanding and clarity, we have split the work into three parts:

Part 1. Impact on related specifications (still waiting for feedback from S-104). 
Part 2. Node-based to cell area-based product
Part 3. Bounding box

The papers are not meant to be seen as a final way to go but rather as a basis for further discussions. As mentioned before, we are hoping that the PT group will contribute to the discussion and bring comments and feedback to the work. We are still looking in to how to solve these issues in practice and we will post more in August, before the upcoming PT14 meeting.

The three parts have been attached as PDF files.
Have a nice summer!

//Anna

[Part_1_Impact on related specifications.pdf](https://github.com/iho-ohi/S-102-Product-Specification/files/12094099/Part_1_Impact.on.related.specifications.pdf)
[Part_2_Node-based to Cell area-based product .pdf](https://github.com/iho-ohi/S-102-Product-Specification/files/12
[Part_3_Bounding box.pdf](https://github.com/iho-ohi/S-102-Product-Specification/files/12094105/Part_3_Bounding.box.pdf)
094102/Part_2_Node-based.to.Cell.area-based.product.pdf)

**Comment by poseiron01** [comment]
Updated Part 1 with the comments from S-104PT
[Part_1_Impact on related specifications_addition.pdf](https://github.com/iho-ohi/S-102-Product-Specification/files/12393949/Part_1_Impact.on.related.specifications_addition.pdf)
//PO

**Comment by AnnaWall01** [comment]
In order to try to reach consensus and close this issue during PT14 SMA have added a summary and suggestions for solutions for everyone to comment on. 
 
**For part 1**. Can we agree and conclude the following:

-The feedback from related specifications and working groups are satisfactory?
-No additional related specification and working group should be requested for feedback?

If agreement in the PT group, our suggestion is therefore:
To follow the recommendations from the feedback.

**Comment by AnnaWall01** [comment]
**For part 2**. With regards to the feedback from part 1, we recommend the following for changing to cell area based products:

In S-102 section 10.2.4. Root BathymetryCoverage, in the BathymetryCoverage feature container group:
-Add attribute dataOffsetCode=5 (barycenter) 
-Use interpolationType=nearestNeighbor 
-commonPointRule=1-4 

Editorial work for section 4. Data Content and Structure. _Add something on cell areas_.
Editorial work for section 7. Data Capture and Classification. _Change to cell- by- cell basis_. 

This is one of (perhaps) many possible solutions. If you have another way of solving this issue, please comment below or at the PT14 meeting.

**Comment by AnnaWall01** [comment]
**For part 3**. As per Finlands [image](https://github.com/iho-ohi/S-102-Product-Specification/issues/29#issuecomment-1497608686), to go for approach no 1.

Add dataOffSetCode=1 into Table 12 BathymetryCoverage feature instance group.

Change definition of the Bbox. Suggestively defined as a rectangle matching the outermost cell boundaries of the S-102. This would also take into account the NoData cells (perhaps even stated explicitly this way) and provide a Bbox in the products CRS. A similar definition could be made for the geographical CRS (WGS84, LL, degrees).

Editorial work for section 5.1. Introduction.

A remaining question on this topic: The connection between Bbox in Root-group and Bbox in BathymetryCoverage feature instance group is unclear. Should the dataOffSetCode also be used in the Root-group?

**Comment by AnnaWall01** [comment]
**For further work**: 

Create a S-100 maintenance proposal to add a new interpolation type “uniform” = Assign the same value as the data point for the cell in which the point is located. Values on cell boundaries determined by commonPointRule.

**Comment by tfilppula** [comment]
Closing as completed, 3.0.0 now has a figure (figure 5) depicting S-102 grid structure.
