### ISSUE TITLE
depthCorrectionType and verticalUncertaintyType

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-102-Product-Specification#30]
With the removal of external ISO metadata files from S-102 2.2.0, there is no place to encode  the attributes _depthCorrectionType_ and _verticalUncertaintyType_ (clause 12.2 "Discovery metadata" in the February draft) nor are any remaining references to them elsewhere than in clause 12.2, which is being deleted as a consequence of the decision to not use external ISO metadata files.

_depthCorrectionType_ and _verticalUncertaintyType_ are therefore being removed under the presumption that they will either be in the "non-navigation" version or will need further discussion for the "navigation" version of S-102. Their respective enumerations are recorded below for future use if needed.

![Tables18-19](https://user-images.githubusercontent.com/51188078/226468475-80b404b5-dd0f-4158-980e-c9a41d6b272f.PNG)

**Comment by poseiron01** [comment]
I think depthCorrectionType can be removed without any problems, I don't se the relevance of it for the end-user. At least not in the navigational product. However the verticalUncertaintyType is something that we need to discuss further. We need to be able to tell the end-user what kind of uncertainty is used in the product.

**Comment by rmalyankar** [comment]
Should _verticalUncertaintyType_ be added to QualityOfSurvey(Coverage) (clause 10.2.8 - Table 14 - Elements of featureAttributeTable compound datatype) or root group metadata (clause 10.2.1 - Table 8 - Root group attibutes), or neither?

**Comment by giumas** [comment]
I agree that we need to inform the end-users on the type of uncertainty. I am unsure how to display this information.

**Comment by rmalyankar** [comment]
It depends on whether _verticalUncertaintyType_ applies over the entire grid for a single coverage feature in S-102, or varies (depending perhaps on the survey, since the grid in any particular S-102 dataset may be computed from different surveys.)

If it can be different in different locations of the coverage feature, the right place would be QualityOfSurvey(Coverage) in Table 14.  In the absence of further comments on this issue, I will so assume.

Being a bathymetry-specific enumeration, it will need a more precise name and definition, since it would ultimately need to be added to the IHO GI Registry:

Name: bathymetricUncertaintyType
Definition: An estimate of the magnitude of the difference between true and estimated bathymetric depth, after all appropriate corrections are made.
Type: Enumeration
Enumeration members: (From Table 19 above, but with "unknown" omitted; "unknown" will be indicated in S-102 by the "fill code" 0; alternatively, "unkownBathymetricUncertaintyType"?).

(All the above is assuming it is included in S-102 2.2.0, which, so far, appears to be what is desired.)

**Comment by RohdeBSH** [comment]
Hi All,

The S-102 does not need any uncertainty information from the point of view of the BSH. ;)

If the vertical uncertainty is required, then it makes sense to specify it in the new metadata coverage. In case of doubt, the value is not unique over the whole S-102 file.

What I don't understand is why the value "Unknown" should be omitted.
This value is important for the BSH because we don't know anything about the uncertainty. The fill value of the uncertainty in the BathymetryCoverage is after all also 1000000 and not zero. Furthermore, we had also agreed that all attributes in the metadata coverage are optional (0…1). Therefore, I am not sure what role a fill value should play here.

**Comment by rmalyankar** [comment]
I sent @hasel001 the Word redline on Thursday night.
Note that _verticalUncertaintyType_ is an enumeration, not an integer or real type. 0 would be the index for the "unknown" in the enumeration. Also that _verticalUncertaintyType_ is used in a compound type, and its value may be known for some partial region of the grid and unknown for another partial region.

As I wrote above, I have already sent the redline. Any further changes would have to be coordinated with or after @hasel001's  transfer of the updates to Metanorma and possibly the next PT meeting.

**Comment by rmalyankar** [comment]
> ... its value may be known for some partial region of the grid and unknown for another partial region.

@RohdeBSH 
> ... In case of doubt, the value is not unique over the whole S-102 file.

This is how I understand it and what the draft I sent yesterday allows, however Edition 2.1 had it in the discovery metadata block and therefore allowed only one value for all grid points populated with bathymetry data.

**Comment by hasel001** [comment]
The vUT information has been included in the featureAttributeTable. While I can't point out specifically when this question was resolved, it appears that we have moved forward. I am closing this issue, but of course participants can raise any part of it again if the present S-102 structure requires modification.
