### ISSUE TITLE
Requesting PT Review for v2.2 -- COB 7 April 2023

### ISSUE THREAD

**Issue by hasel001** [iho-ohi/S-102-Product-Specification#35]
Good afternoon Project Team!

I have put Raphael's latest changes (as well as SMA-submitted changes from over a month ago) into the Developing branch.

Julia has asked if we can have a proposed version 2.2.0 to her by the beginning of next week. In view of that requirement:

Indicate here one of the following 3 options:
(a) Concur with all commits as listed in https://github.com/iho-ohi/S-102-Product-Specification/pull/24
(b) Concur pending changes (and specify those changes)
(c) Do not concur at this time

If possible, please make your selection before COB on 7 April.

Thanks for all your hard work and attention. Please don't hesitate to reach out if you have questions or issues. I really appreciate all your help and support.

Best regards,

Lawrence

**Comment by rmalyankar** [comment]
The support file material appears to be there still? Specifically -

- Clause 12 table 1 -  row for support file discovery metadata in S100_ExchangeCatalogue table becomes redundant if support files are not used.
- Clause 12: The whole sub-clause Support File Metadata would be redundant including tables 17-21, if support files are not allowed. (The new UML diagram does not have the classes for support file metadata.)

**Comment by RohdeBSH** [comment]
Our answer is available in the form of a review in Merge/Pull Request #24.

Based on our findings in the review, we are leaning towards (c). From our point of view, this version cannot be given to Julia.

**Comment by hasel001** [comment]
1. I apologize if you have received scores of notifications because of all of my changes/reversions. I was beginning to panic because I couldn't get any artifacts to export. But all is well now.

2. I have made the edits @rmalyankar  mentioned  and addressed most of the items in the @RohdeBSH review of #24 .

3. @RohdeBSH and I had a phone conversation this morning/afternoon. BSH are generally happy with the changes and are okay with v2.2 going to Julia. Daniel mentioned that, in order to preserve comments while discussion is still ongoing, it would be better to only provide Julia with the (Word/PDF) exports without actually performing a merge yet. I agree with him.

4. So, please continue to let me know (by COB 7 Apr if possible) if you:
(a) Concur with sharing the document in its present form (from the Developing branch)
(b) Concur pending specified changes
(c) or Do not concur with sharing

Thanks for all your help and patience. Hopefully we can come to an agreement on this version soon. Have a great rest of your day!

Best regards,

Lawrence

**Comment by PaulAusHydro** [comment]
Concur.

Though, I've been doing a little tinkering with the S-102 file size indications contained in Table 16.  I've always found that table quite hard to interpret and had a suspicion that the data did not conform to what I was getting when exporting S-102 products.

So I added some New Zealand S-102 file size export data (in addition to the Aus data) to my earlier analysis regarding S-102 file sizes.  The fitted model of S-102 file sizes changed a little as expected.  What I then did was to calculate the file sizes using the parameters contained in Table 16 of the S-102 product spec.  There is quite a bit of difference (order of magnitude), particularly for smaller grid resolutions.  See attached PDF version of the spreadsheet.

My personal view is in the next version of the product spec we should revise Table 16 to something else.  With more S-102 datasets to hand we could add more data to the empirical model fit and potentially include the models or isoline graphs in the product spec.

[S-102_file_size_experiment_v2.pdf](https://github.com/iho-ohi/S-102-Product-Specification/files/11165069/S-102_file_size_experiment_v2.pdf)

**Comment by rmalyankar** [comment]
I  concur with (a). The following changes should be applied if time permits:

1. The language in clause 11.3 (Exchange Set) still mentions support files - please see the redline I sent for revisions, in that the text of the list looks like this.

> 1)	An S-102 Exchange Set must contain an Exchange Set Catalogue, CATALOG.XML, its digital signature CATALOG.SIGN, and may contain any number of S-102 conformant dataset files, support files, and Catalogue files. 
> 2)	All content must be placed inside a top root folder named S100_ROOT. This is the only top level root folder in an Exchange Set containing only S-100 products. 
> 3)	The S100_ROOT folder must contain a subfolder named S-102. This subfolder holds content specific to the S-102 Product Specification. 
> 4)	The S-102 subfolder must contain subfolders for the component dataset files (DATASET_FILES) and Catalogues (CATALOGUES) as required. 
> 5)	The required Exchange Set Catalogue XML document instance must be named CATALOG.XML and placed in the S100_ROOT folder, together with its digital signature (CATALOG.SIGN) file. All other digital signatures are included within their corresponding resource metadata records in the CATALOG.XML. 
> 6)	Support files are not allowed in S-102 exchange sets for this edition of S-102. 

2. Figure 9 mentions QualityOfSurveyCoverage instead of QualityOfSurvey and should be replaced with the figure below (I'll send a Powerpoint file by email).

![Figure9](https://user-images.githubusercontent.com/51188078/230237971-834b5b55-3f83-4bc0-9cf9-8d4e5504f7b0.png)

There are other minor editorial issues but I think they are less important than the above.

**Comment by PaulAusHydro** [comment]
I had another comment for discussion.  In the product spec there is 12.5.1 S100_NavigationPurpose...

just noting here that the numbering convention is opposite to S-57 (not sure about S-101??) usage band convention.
In table 12.5.1 nav purpose 1 = large scale port usages and 3 = small scale ocean crossings 

In S-57 land, usage band 5 = large scale port type charts
usage band 3/2/1 = smaller scale nav products

I'm presuming S-101 products will mirror S-57 usage codes, and if so, is/should S-102 usage codes be switched around for consistency?

**Comment by hasel001** [comment]
@PaulAusHydro , thanks for those comments. I am deferring to those more knowledgeable than myself for their replies, but I want you to know I've heard and do appreciate your input.

@rmalyankar , I just made the Exchange Set changes. Before I saw your last post, I independently ran across the error in the old figure and made the SmartArt to best match the old one. Do you recommend I go with the one that includes Level0/Root? I'm happy with either one as long as we have a general consensus. Thanks for those catches, and I apologize for missing them in the first place.

**Comment by AnnaWall01** [comment]
SMA concur with sharing the document (a). Some minor observations we picked up: 

- Some of the hyperlinks/URLs are not working in section 1.2 References. Seems to be the IHO-links.  

- Also, the wrong edition is mentioned in section 1.2 References; S-100 should be edition 5.0.0 and S-44 which should be edition 6.0.0.

- Since section 12.7.4 S.100_VerticalAndSoundingDatum has been completely removed;
Refer to GI Registry in section 5.3 Vertical Coordinate Reference System, in the last paragraph. Also refer to GI Registry in Table 8 Root Group attributes row 26. Vertical Datum.

**Comment by tfilppula** [comment]
Concur with (a).

I noted that there is still one mention of the _tracking list_ in https://github.com/iho-ohi/S-102-Product-Specification/blob/Developing/sources/2.2.0/sections/04-data_content_struct.adoc: 
"Thus, the Bathymetric Surface Product is a hybrid of coverages, as defined in [part=8](https://github.com/iho-ohi/S-102-Product-Specification/blob/Developing/sources/2.2.0/sections/04-data_content_struct.adoc#iho-s100), and metadata packages as defined in [part=4](https://github.com/iho-ohi/S-102-Product-Specification/blob/Developing/sources/2.2.0/sections/04-data_content_struct.adoc#iho-s100), together with a point set tracking list."

I guess this should be removed.

**Comment by hasel001** [comment]
@AnnaWall01 Thanks for catching those errors. Until Metanorma is updated for references, I intend to manually make reference-based fixes post-export. 

For mentions of the GI Registry, I have what may be a stupid question. 

I logged into the registry, and I wasn't able to find the relevant search parameters (for example, to get the allowable values for VerticalAndSoundingDatum). I want to go through the process myself so I can understand how to word the mention in our spec. 

What search terms should I be using to retrieve that information?

**Comment by rmalyankar** [comment]
@hasel001 - about the updated Figure 9, without Level 0 is fine, the important thing is changing QualityOfSurveyCoverage to QualityOfSurvey in the three places it appears in Levels 1 and 2. (I see my figures are missing a box so go with yours either with or without Level 0.)

About the registry and S100_VerticalAndSoundingDatum - the GI registry does not have S100_VerticalAndSoundingDatum as such (the registry doesn't currently include any metadata elements) but it does have the simple attribute _verticalDatum_ in the data dictionary register; searching for "datum" by name will find that. S-100 5.0.0 Part 17 says:
> The numeric codes are the codes specified in the IHO GI Registry for the equivalent listed values of the IHO Hydro domain attribute Vertical Datum, since the Registry does not at present (20 June 2018) contain entries for Exchange Set metadata and dataset metadata attributes.

@PaulAusHydro - I presume S-101 will adhere to the S-100 specification of S100_NavigationPurpose but it might be worth confirming with the chairs of the S-101 PT and S-100 WG.

**Comment by hasel001** [comment]
@rmalyankar, @tfilppula , @AnnaWall01 -- Thank you all. I've made edits as appropriate from your comments.
@PaulAusHydro -- Thank you. I've verified that our numbering is consonant with S-100, and I agree that it will be worthwhile to check for consistency with S-101 as things move forward.

I am downloading the artifacts now, and I will make manual edits to the Word doc and PDF to ensure the correct versions are referenced before sending on to Julia.

I very much appreciate everyone's assistance in getting v2.2 ready to move. Please continue to create issues as the need arises, and please keep contacting me if you have any questions or concerns. Thank you all so much!

**Comment by PaulAusHydro** [comment]
This is the S-101 product spec usage code indication, so yes, S-102 usage aligns with S-101 usage.  No further action required.

![image](https://user-images.githubusercontent.com/130008223/231012333-fe372c60-69ba-4b5f-83f5-ed60fc6b6703.png)
