### ISSUE TITLE
S-102 PT Secretary Role

### ISSUE THREAD

**Issue by hasel001** [iho-ohi/S-102-Product-Specification#36]
Good morning Project Team!

@AnnaWall01 has been nominated to serve as the S-102 PT Secretary. I am thankful for her willingness to serve, and I predict she would excel in the role.

I move that we install her as secretary, and I open the floor for a second.

Thank you!

Best regards,

Lawrence

**Comment by tfilppula** [comment]
I second it too.

**Comment by hasel001** [comment]
Excellent! Thanks to everyone for supporting @AnnaWall01 and the rest of this Project Team. It is truly a privilege to work with such a fantastic group!

Have a great rest of your day!

Best regards,

Lawrence
