### ISSUE TITLE
Planned VTC -- Please Respond by 28 April

### ISSUE THREAD

**Issue by hasel001** [iho-ohi/S-102-Product-Specification#37]
Good morning Project Team!

We are considering holding the next (S-102PT13) VTC from 1 to 2 June, from 1100 to 1400 UTC both days. Please respond (here in GitHub or via email) with your availability for that timeframe. If possible, please respond by Friday, 28 April. Thank you!

Best regards,

Lawrence

**Comment by JLeDeunf** [comment]
Hi Lawrence,
Unfortunately not available for this date.
Have a nice day,
Julian.

**Comment by giumas** [comment]
I am also unlikely able to join on those dates.

**Comment by RohdeBSH** [comment]
I am also available on June 1 and 2.

**Comment by tfilppula** [comment]
I am available on the proposed dates.

**Comment by anthonyklemm** [comment]
I'll be out to sea at that time, so I'm a doubtful/maybe for those dates.

**Comment by hasel001** [comment]
For the dates of 1 to 2 June, we have:

17 who can attend
2 who might can attend
3 who cannot attend

So we have decided to go forward with the VTC (S-102PT13). The dates will be 1 to 2 June 2023, and the VTC will run from 1100 to 1400 UTC both days.

1. Hearing https://github.com/iho-ohi/S-102-Product-Specification/issues/25 , @AnnaWall01 , Lynn, and I will work diligently to have an agenda distributed well in advance.
2. @AnnaWall01, in order to have a draft agenda distributed by 24 May, can you please propose a deadline for submission of agenda items?
3. It is understood that later submissions may be inevitable, and that is fine. However, submissions before the deadline will have priority consideration while the remainder will be considered on a not-to-interfere basis.
4. You can submit agenda items and other questions:
  a. By creating an issue on this repo, or
  b. By emailing me, @AnnaWall01 , and/or Lynn.
5. I will email Yong and ask him to publish information about the VTC on https://online.iho-khoa.kr/registration.

Thanks to everyone for all the inputs and all the help. Please let us know if you have any questions or issues. Thank you, and have a great weekend!
