### ISSUE TITLE
Deployment to GitHub Pages via actions-mn/build-and-publish not working

### ISSUE THREAD

**Issue by ronaldtse** [iho-ohi/S-102-Product-Specification#41]
Will be addressed here:
* https://github.com/actions-mn/build-and-publish/issues/9

**Comment by hasel001** [comment]
Because the build/deploy actions seem to be working correctly now, I assume we can close this issue. @ronaldtse , is that your assessment as well?

**Comment by ronaldtse** [comment]
@hasel001 Agree, let's close this. Thanks!
