### ISSUE TITLE
Bounding Longitudes Question from NOAA/SeaIQ

### ISSUE THREAD

**Issue by hasel001** [iho-ohi/S-102-Product-Specification#45]
Barry Gallagher (NOAA, barry.gallagher@noaa.gov) presents a question below (edited for brevity) from @markghayden (SeaIQ, mark@seaiq.com). I am posting it here to ensure we are all working from a common interpretation. All comments and questions are welcome.

* * *
>Hi Jeff, @anthonyklemm and Lawrence,
SeaIQ's (Mark) point about the bounding longitudes seems to be correct.  In the original code, I received from Stacey Johnson, the output coordinates in the bounding boxes were in the reference system of the data.  The spec was also less explicit in 2.0 about what it should be.  In 2.1 it now reads that the bounds are in degrees while the gridOriginLatitude/Longitude is in the units of the reference system (meaning that the name may be latitude but the units are meters for UTM).
I'll make a change in the S102 code to correct this unless Anthony or Lawrence disagree with that interpretation.  It should not be affecting drawing the raster as that should be using the gridOrigin and gridSpacing elements which would be in UTM meters (and should match the bounding box values currently until I fix it).
Barry Gallagher

>>Hi Jeffrey,
In reviewing the newest files, I noticed that the geographic bounding box in the root group appears to be using coordings in the projection.  My understanding  (from S-102 10.2.1) was that these coordinates should be decimal degrees.  See below.  Having said that, the remainder of the description is confusing.  Can you shed some light on this?
Best, Mark

>>>From 'h5dump -A' output, you can see the longitude is clearly not in -180..180 range.
ATTRIBUTE "eastBoundLongitude" {
  DATATYPE  H5T_IEEE_F64LE
  DATASPACE  SCALAR
  DATA {
  (0): 388975
  }
}
>>><img width="794" alt="attachment" src="https://github.com/iho-ohi/S-102-Product-Specification/assets/31776042/b161ab40-f4fb-4c96-a9f3-d5e1e535c61c">

**Comment by RohdeBSH** [comment]
Hello,

I'm not entirely aware of the problem.
I find the S-102 Ed. 2.1.0 very clearly described at this point.
As you may know, Germany uses the projected coordinate system EPSG:32632 (WGS84/UTM32N) within S-102.
The coordinate systems allowed for S-102 are described in section 5.1 table 1.
Table 8 of Section 10.2 describes that, although we use a projected coordinate system (EPSG:32632), we have to specify the bounding box in WGS84 (baseCRS to EPSG:32632)
The description of the "baseCRS" is again contained in the S-100 Ed. 4.0.0 Part 6 Section 6-4.3.2 Table 6-5.
![S-102_BBOX](https://github.com/iho-ohi/S-102-Product-Specification/assets/85698889/80090597-9ccc-4aea-b6d6-0cca3809470f)

**Comment by hasel001** [comment]
This issue was discussed during PT13. In order for @anthonyklemm, @markghayden, etc. to have the opportunity to respond (and to foster further discussion in general), we will continue to keep this issue open.

**Comment by hasel001** [comment]
Chair has action to either (a) determine if the issue has been resolved (via new DD language in S-100 Ed. 5.2.0) or (b) consult with those members who raised the issue to determine its status. If appropriate, chair will close this issue (per PT16 decision).

**Comment by hasel001** [comment]
Upon a fresh read of all the relevant information, I find the PS to be clear in what it describes/mandates. I am closing this issue. If any related matters arise, participants are encouraged to open another issue.
