### ISSUE TITLE
Artifacts other than Product Specification document components

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-102-Product-Specification#52]
What are the appropriate locations for artifacts under development which are not part of the product specification document but are associated to a specific edition of the Product Specification? For example:

- XML feature catalog
- Portrayal catalog
- Excel spreadsheet file with product-specific validation checks

(The NIWC portrayal catalog is currently on Google Drive and linked from the Wiki for this repository, but I think that is a temporary expedient?)

**Comment by RohdeBSH** [comment]
In my opinion here:
sources/<edition>/FC     -> e.g. sources/2.2.0/FC
sources/<edition>/PC
sources/<edition>/ValidationChecks

The directories are then in the metanorma structure, but are not used and therefore do not interfere.

**Comment by hasel001** [comment]
At PT14, we decided to implement this structure. Lawrence has this action.

**Comment by hasel001** [comment]
I have added the folders as we agreed. Thanks everyone!

**Comment by ronaldtse** [comment]
Sorry for the late chime in here @hasel001 . I believe the suggestions by @RohdeBSH are perfect and this also allows a potential inclusion from the S-102 Metanorma document to include such content if necessary. 

For example, the S-102 PDF could also include these files as attachments if desired.
