### ISSUE TITLE
DCF for BathymetryCoverage and QualityOfSurvey

### ISSUE THREAD

**Issue by HolgerBothien** [iho-ohi/S-102-Product-Specification#56]
In an S-102 datasets two types of features exists **_BathymetryCoverage_** and **_QualityOfSurvey_**.
The first has its values directly in a regular gridded HDF5 dataset '_values_' as pairs of depth and uncertainty.
The second has integer numbers in the regular grid the have to be used as indices in a separate HDF5 dataset '_featureAttributeTable_'.
This is new in S-102 and new in S-100 Ed. 5. It is defined by the Data Coding Format (DCF) value of 9.
In the current version of S-102 (1.2.0) The DCF value is defined as 9 for both types of features.
This seems to be wrong the **_BathymetryCoverage_** feature should have a DCF of 2 and the **_QualityOfSurvey_** feature a DCF of 9.
There a several places where it is mentioned that the Metadata attributes of the feature instances are the same. 
This is not true. The DCF should be encoded different and only the other attributes are identical.

**Comment by tfilppula** [comment]
Referring to #13 shouldn't it be _QualityOfBathymetryCoverage_ instead of _QualityOfSurvey_?

**Comment by HolgerBothien** [comment]
I have used the name as used in the PS, but whatever the name is this issue is about the DCF. 
The naming is a separate issue but the PS needs to be corrected for that as well.

**Comment by RohdeBSH** [comment]
That's correct Holger.
BathymetryCoverage = DCF 2
QualityOfBathymetryCoverage/QualityOfSurvey = DCF 9

**Comment by RohdeBSH** [comment]
Change Value: it has to be "2"

https://github.com/iho-ohi/S-102-Product-Specification/blob/dfbcb1747d12f8b1d56325f1e89cc24c81f662a3/sources/2.3.0/sections/10-data_product_format.adoc?plain=1#L577
---
Adjust text.
The attributes are the same except for the DataCodingFormat. DCF must be "9".

https://github.com/iho-ohi/S-102-Product-Specification/blob/dfbcb1747d12f8b1d56325f1e89cc24c81f662a3/sources/2.3.0/sections/10-data_product_format.adoc?plain=1#L825
