### ISSUE TITLE
List of vertical datums

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-102-Product-Specification#60]
Another point, may not fit directly to this:
In table 8 for vertical Datum it says: 
Numeric code from IHO GI Registry Vertical Datum attribute except 

- 47 (seaFloor) 
- 48 (seaSurface) 
- 49 (hydrographicZero).

It would be better to have a positive list of values that are allowed instead of refering to a living docoment where every day new values can appear.

_Originally posted by @HolgerBothien in https://github.com/iho-ohi/S-102-Product-Specification/issues/53#issuecomment-1706482563_

**Comment by rmalyankar** [comment]
I have no comment about this suggestion.

**Comment by RohdeBSH** [comment]
BSH prefers a positive list. Otherwise, the implementation has to change every time the registry is updates.

**Comment by RohdeBSH** [comment]
PT15 - create a whitelist in the PS

**Comment by hasel001** [comment]
Completed after reaching agreement during PT15. lhh
