### ISSUE TITLE
Annex F

### ISSUE THREAD

**Issue by AnnaWall01** [iho-ohi/S-102-Product-Specification#61]
Sweden suggest removal of Annex F from the S-102 PS. There is no need for this information in S-102.

We suggest either to
1.	Remove the annex entirely from the PS or, 
2.	Keep the first page and the title and refer to document C-13 instead.

It has also been noted that some of the information in the annex is incorrect. Please see comments in the attached PDF, page no 63 to 65.

[S-102 Ed.2.2_2023-04_commented (002).pdf](https://github.com/iho-ohi/S-102-Product-Specification/files/12800036/S-102.Ed.2.2_2023-04_commented.002.pdf)

**Comment by RohdeBSH** [comment]
Hi @AnnaWall01,

We have no problem with removing Annex F.
You have our consent.

**Comment by tfilppula** [comment]
Also support removing annex F.

**Comment by giumas** [comment]
Support for removal of Annex F. 
@AnnaWall01, what about Annex E? What is the point of having it without something concrete being worked on?

**Comment by AnnaWall01** [comment]
Decision at PT15 to remove Annex F from PS. @hasel001 if you can make the practical work of removing it from the PS?

**Comment by hasel001** [comment]
I will happily take on that action.

**Comment by hasel001** [comment]
I finally resolved this issue by making the appropriate changes this morning.
