### ISSUE TITLE
"Definitions" section should follow IHO S-97 document structure

### ISSUE THREAD

**Issue by ronaldtse** [iho-ohi/S-102-Product-Specification#66]
The S-102 document is governed by the S-97 Guidelines since it belongs to S-100.

The current "Terms, definitions and abbreviations" clause is actually in the ISO structure, not IHO typical structure or the IHO S-97 structure.

The IHO typical structure is described here:
* https://www.metanorma.org/author/iho/authoring-guide/terms-definitions/

## Standalone "Definitions" clause

<img width="815" alt="Screenshot 2023-11-04 at 5 29 07 PM" src="https://github.com/iho-ohi/S-102-Product-Specification/assets/11865/3a646a97-8a9f-4f37-b02a-ece7e87f0cf5">

## Combined "Definitions, acronyms and abbreviations" clause

<img width="798" alt="Screenshot 2023-11-04 at 5 29 28 PM" src="https://github.com/iho-ohi/S-102-Product-Specification/assets/11865/864464a8-9f34-4436-bb66-108274efd6f5">

## Actions to be taken

IHO S-97 specifies that the S-100 Product Specification documents need to follow this structure. The Metanorma team needs to ensure this structure is adhered to for S-100 PS documents.

<img width="635" alt="Screenshot 2023-11-08 at 5 01 30 PM" src="https://github.com/iho-ohi/S-102-Product-Specification/assets/11865/5345a353-49b0-41a5-8cc3-383c29a2c52d">

**Comment by rmalyankar** [comment]
1. "Use of language" is not a sub-topic of "Terms, definitions and abbreviations" and should be a separate sub-clause at the same level as "Terms, definitions, and abbreviations" (e.g., clause 1.4 Use of Language).
2. Note the style used for terms and definitions (these conventions are used in S-100 Edition 5.2.0 as well as S-97 1.1.0 itself):
    - Individual terms do _not_ get their own clause/heading numbers.
    - Terms begin with lower case letters.
    - Definitions also begin with lower case letters.
    - The source is cited in box brackets after the definition, sometimes on the same line, sometimes on the next line. (I recommend the same line, so as not to waste space on the page with an additional minimally filled line)

![Screenshot S-100-5_2_0-AnnexA](https://github.com/user-attachments/assets/c0e3b157-3df9-46aa-b0a8-7ee5b86f5217)

**Comment by hasel001** [comment]
The content from this issue has been migrated to [Issue 187 on metanorma-iho](https://github.com/metanorma/metanorma-iho/issues/187). I am marking this issue closed to fulfill my action from S-102PT19.
