### ISSUE TITLE
[PT11 Action XX] - Create Adoc-files for edition 2.2.0

### ISSUE THREAD

**Issue by RohdeBSH** [iho-ohi/S-102-Product-Specification#7]
For edition 2.2.0, the adoc files still need to be created to start working in GitHub.

- [x] Include the BSH table in the draft
- [x] Ask Ribose to create the adoc files

**Comment by RohdeBSH** [comment]
Product specification document with corrected table 10-7.

[S-102_Ed2.2.0_Draft_Redline_plus_RM_plusLHHedit_8Dec2022.docx](https://github.com/iho-ohi/S-102-Product-Specification/files/10235708/S-102_Ed2.2.0_Draft_Redline_plus_RM_plusLHHedit_8Dec2022.docx)

**Comment by RohdeBSH** [comment]
Email sent to Mr. Tse from Ribose.

[Email_to_mrTse_Adoc_conversion.pdf](https://github.com/iho-ohi/S-102-Product-Specification/files/10235909/Email_to_mrTse_Adoc_conversion.pdf)

**Comment by ronaldtse** [comment]
This has been implemented in #10.
