### ISSUE TITLE
Image Updates needed

### ISSUE THREAD

**Issue by RohdeBSH** [iho-ohi/S-102-Product-Specification#76]
Hi,

While renaming the metadata coverage from QualityOfSurvey to QualityOfBathmetryCoverage, I noticed that the images still need to be updated ( 4ae4ca550b1dc083f18875395c85682c1a5aa853 ).
Unfortunately, this affects some images.
However, I do not have access to the original data. That's why I prefer SVG images instead of PNG.

figure-data-set-structure-s102.png
???figure-coverage-structure-of-s102.png????
figure-hierarchy-of-s102-data-product.png
figure-hierarchy-of-s102-data-product-nozero.png
figure-overview-structure-s102.png

**Comment by rmalyankar** [comment]
I have uploaded the 2.2 model as an XMI file, which Enterprise Architect can import into the S-100 5.1 UML model from the S-100 repository. That contains the UML figures. I don't have diagram files for the other figures - but I think edited one of them directly in the Word version we had then.

**Comment by RohdeBSH** [comment]
Hi @rmalyankar,

Thanks for your help.
Unfortunately, I'm not familiar with the Enterprise Architect software. I'm not even sure if we have the software available at BSH. Could you perhaps demonstrate it at the next meeting? I don't think I'm the only one who has no idea what to do now.

@hasel001 @AnnaWall01 : Please put this on the agenda for PT16.

**Comment by hasel001** [comment]
Images have been updated with guidance/assistance from several PT members. I will now close the issue.
