### ISSUE TITLE
Adaptation of S-100 Ed. 5.2.0

### ISSUE THREAD

**Issue by RohdeBSH** [iho-ohi/S-102-Product-Specification#77]
Hi,

According to section 2.5 of S-102, this standard is based on S-100 Ed 5.0.0.
The IHO has decided with the Circular Letter 43/2023 that PS of phase 1 must be based on S-100 Ed. 5.2.0 (see point 3 & 4).
[https://iho.int/uploads/user/circular_letters/eng_2023/CL43_2023_EN_v1.pdf](https://iho.int/uploads/user/circular_letters/eng_2023/CL43_2023_EN_v1.pdf)

```
3. The S-100WG decided that, in order to correct the digital signature algorithm and amend
key lengths, a new Edition 5.2.0 of S-100 is necessary before the Phase 1 Product Specifications
in their Edition 2.0.0 can be finalized. In order to accomplish this, the HSSC intends to issue an
HSSC Letter by the end of January 2024 with a mid-March endorsement deadline for HSSC
Members. Following this endorsement, an IHO CL will be issued with an IHO Member States
response deadline at the end of May 2024.
```

```
4. Following the expected publication of the adoption of S-100 5.2.0 in mid June 2024,
WGs endorsement of Phase 1 Product Specifications can begin. WGs endorsement of Phase 1
Specifications must be concluded by mid-August 2024 but may be done earlier. Phase 1
Product Specifications will then be issued for HSSC MS endorsement by mid-October 2024.
```

So we have to check the S-102 again to see if it is S-100 5.2.0 compliant and adjust the references.

**Comment by skjeves** [comment]
Fully agree, this was also a clear recommendation from S100WG:
Agenda Item 3.7: S-100WG8 recommended the S-102 Product Specification should be aligned with Edition 5.2.0 of S-100 because of the S-100 Part 15 digital signature correction.

**Comment by tfilppula** [comment]
Just as a note for later action: 
In S-100 5.2.0 it is mandatory to use 0-based indexing for grids (10c-9.1.1 Array and grid element indexing).

Therefore section 4.4.2.1. S-102 coverages and Figure 5 (in S-102 2.2.0) need to be changed.

**Comment by hasel001** [comment]
Per our decision during S-102PT17, a Small Group Discussion regarding S-102 PS alignment with S-100 Ed. 5.2.0 will take place via [Google Meet](https://meet.google.com/zzt-khes-yto) on Thursday, 6 June 2024 from 1300 to 1500 UTC+2/CEST. 

The overall goal is to ensure all portions of the S-102 PS are reviewed/modified to align with S-100 Ed. 5.2.0.

The desired outcome from this meeting is to assign any remaining portions to a responsible person and to identify a deadline for review/modification. 

Thank you!

**Comment by RohdeBSH** [comment]
This branch [77-adaptation-of-s-100-ed-520](../tree/77-adaptation-of-s-100-ed-520) is used to adapt the S-102 to the S-100 edition 5.2.0.
The following tasks still need to be completed before the branch can be merged.

## Sections
- [ ] Document History - [/sources/3.0.0/sections/00-document-history.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/00-document-history.adoc)
- [ ] Overview - [/sources/3.0.0/sections/01-overview.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/01-overview.adoc)
- [ ] Specification Scope - [/sources/3.0.0/sections/02-spec_scope.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/02-spec_scope.adoc)
- [ ] Data Product Identification - [/sources/3.0.0/sections/03-data_product_id.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/03-data_product_id.adoc)
- [ ] Data Content and Structure - [/sources/3.0.0/sections/04-data_content_struct.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/04-data_content_struct.adoc)
- [ ] Coordinate Reference Systems (CRS) - [/sources/3.0.0/sections/05-coord_ref_system.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/05-coord_ref_system.adoc)
- [ ] Data Quality - [/sources/3.0.0/sections/06-data_quality.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/06-data_quality.adoc)
- [ ] Data Capture and Classification - [/sources/3.0.0/sections/07-data_cap_class.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/07-data_cap_class.adoc)
- [ ] Data Maintenance - [/sources/3.0.0/sections/08-data_maintenance.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/08-data_maintenance.adoc)
- [ ] Portrayal - [/sources/3.0.0/sections/09-portrayal.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/09-portrayal.adoc)
- [ ] Data Product Format (Encoding) - [/sources/3.0.0/sections/10-data_product_format.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/10-data_product_format.adoc)
- [ ] Data Product Delivery - [/sources/3.0.0/sections/11-data_product_delivery.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/11-data_product_delivery.adoc)
- [ ] Metadata - [/sources/3.0.0/sections/12-metadata.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/12-metadata.adoc)
- [ ] Annex Data Classification and Encoding Guide - [/sources/3.0.0/sections/aa-data_class_enc_.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/aa-data_class_enc_.adoc)
- [ ] Annex Normative Implementation Guidance - [/sources/3.0.0/sections/ac-norm_impl_guidance.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/ac-norm_impl_guidance.adoc)
- [ ] Annex Portrayal Catalogue - [/sources/3.0.0/sections/ae-portrayal-catalogue.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/ae-portrayal-catalogue.adoc)
- [ ] Annex S-102 Dataset Size and Production - [/sources/3.0.0/sections/af-dataset_size_production.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/af-dataset_size_production.adoc)
- [ ] Annex Multi-Resolution Gridding - [/sources/3.0.0/sections/ah-multi-res_gridding.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/ah-multi-res_gridding.adoc)
- [ ] Annex Gridding Full Resolution Source Bathymetry and its Relationship to a Charted Sounding - [/sources/3.0.0/sections/ai-gridding_full.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/ai-gridding_full.adoc)
- [ ] Annex Validation Checks - [/sources/3.0.0/sections/aj-validation-checks.adoc](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/sections/aj-validation-checks.adoc)

## Images
- [ ] [/sources/3.0.0/images/figure-charted-sounding-vs-6-metre-s102-grid.png](../tree/77-adaptation-of-s-100-ed-520sources/3.0.0/images/figure-charted-sounding-vs-6-metre-s102-grid.png)
- [ ] [/sources/3.0.0/images/figure-components-and-associated-metadata-for-the-s102-exchange-set.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-components-and-associated-metadata-for-the-s102-exchange-set.png)
- [ ] [/sources/3.0.0/images/figure-coverage-structure-of-s102.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-coverage-structure-of-s102.png)
- [ ] [/sources/3.0.0/images/figure-data-set-structure-s102.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-data-set-structure-s102.png)
- [ ] [/sources/3.0.0/images/figure-feature-association.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-feature-association.png)
- [ ] [/sources/3.0.0/images/figure-hierarchy-of-s102-data-product.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-hierarchy-of-s102-data-product.png)
- [ ] [/sources/3.0.0/images/figure-hierarchy-of-s102-data-product.svg](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-hierarchy-of-s102-data-product.svg)
- [ ] [/sources/3.0.0/images/figure-hierarchy-of-s102-data-product-nozero.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-hierarchy-of-s102-data-product-nozero.png)
- [ ] [/sources/3.0.0/images/figure-implementation-of-classes.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-implementation-of-classes.png)
- [ ] [/sources/3.0.0/images/figure-informative-grid-extents-for-a-10mb-uncompressed-dataset.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-informative-grid-extents-for-a-10mb-uncompressed-dataset.png)
- [ ] [/sources/3.0.0/images/figure-informative-grid-extents-for-a-256mb-uncompressed-dataset.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-informative-grid-extents-for-a-256mb-uncompressed-dataset.png)
- [ ] [/sources/3.0.0/images/figure-outline-of-the-generic-data-file-structure.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-outline-of-the-generic-data-file-structure.png)
- [ ] [/sources/3.0.0/images/figure-overview-structure-s102.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-overview-structure-s102.png)
- [ ] [/sources/3.0.0/images/figure-realization-of-the-exchange-set-classes.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-realization-of-the-exchange-set-classes.png)
- [ ] [/sources/3.0.0/images/figure-relationship-between-exchange-catalogue-discovery-metadata-and-dataset.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-relationship-between-exchange-catalogue-discovery-metadata-and-dataset.png)
- [ ] [/sources/3.0.0/images/figure-s52-depth-zone-colouring-for-day.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s52-depth-zone-colouring-for-day.png)
- [ ] [/sources/3.0.0/images/figure-s102-cell-area-and-Bbox.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-cell-area-and-Bbox.png)
- [ ] [/sources/3.0.0/images/figure-s102-discovery-metadata.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-discovery-metadata.png)
- [ ] [/sources/3.0.0/images/figure-s102-exchange-set.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-exchange-set.png)
- [ ] [/sources/3.0.0/images/figure-s102-exchange-set-catalogue.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-exchange-set-catalogue.png)
- [ ] [/sources/3.0.0/images/figure-s102-exchange-set-class-details.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-exchange-set-class-details.png)
- [ ] [/sources/3.0.0/images/figure-s102-grid-cell-location.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-grid-cell-location.png)
- [ ] [/sources/3.0.0/images/figure-s102-grid-node.location.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-grid-node.location.png)
- [ ] [/sources/3.0.0/images/figure-s102-grid-point-location.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-grid-point-location.png)
- [ ] [/sources/3.0.0/images/figure-s102-logo.svg](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-logo.svg)
- [ ] [/sources/3.0.0/images/figure-s102-quality-metadata.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-quality-metadata.png)
- [ ] [/sources/3.0.0/images/figure-s102-signal-flags.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-signal-flags.png)
- [ ] [/sources/3.0.0/images/figure-s102-signal-flags-swag.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-signal-flags-swag.png)
- [ ] [/sources/3.0.0/images/figure-s102-structure-metadata.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-structure-metadata.png)
- [ ] [/sources/3.0.0/images/figure-s102-tiling-scheme.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-s102-tiling-scheme.png)
- [ ] [/sources/3.0.0/images/figure-sonar-footprint-at-nadir.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-sonar-footprint-at-nadir.png)
- [ ] [/sources/3.0.0/images/figure-sun-illuminated-and-static-flat-shading.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-sun-illuminated-and-static-flat-shading.png)
- [ ] [/sources/3.0.0/images/figure-swath-coverage-of-survey-vessel.png](../tree/77-adaptation-of-s-100-ed-520/sources/3.0.0/images/figure-swath-coverage-of-survey-vessel.png)

**Comment by hasel001** [comment]
At today's small group discussion meeting, the following decisions resulted:

1. As edited in the above comment, incomplete sections of the document have been assigned for review.
2. Reviewers will try to complete their reviews as close to 14 June as possible. (It is understood that some sections will necessarily take longer.)
3. Lawrence will finish the small edits to the Metadata Reference pull request and merge it.
4. Image edits will be handled as a part of each section to which the images belong. If you are reviewing a section and require image changes, Lawrence requests that you mark up the images requiring changes and send the markup to him. In turn, he will use EA to generate the new image.
5. Lawrence has reached out to Jeff Wootton to obtain the latest copy of S-100 Ed. 5.2.0. He will report back to the PT Monday or Wednesday (during PT18) in order to resolve [this issue](https://github.com/iho-ohi/S-102-Product-Specification/issues/69).

Please let me know if it seems I've missed anything. Thank y'all for a great meeting!

**Comment by hasel001** [comment]
I have finished reviewing and editing everything that lacked a check mark (and several items that already had one but needed a recheck after the real 5.2 came out). Please take a look when you have a few moments. Apart from the results of our upcoming decision on Thursday, I think we have much of what we need to put 3.0 under a PT review period. Before that happens, though, I'd like the people who have been focusing on 5.2 alignment to take a look and share their opinions. Thanks!
