### ISSUE TITLE
bathyCoverage name and definition

### ISSUE THREAD

**Issue by rmalyankar** [iho-ohi/S-102-Product-Specification#80]
Attributes for DCF 9:

1.  _bathyCoverage_ (Flag for  nodes  populated by interpolation) needs a new name, the registry already contains the concept _Bathymetric Coverage_ (Extent to which an area has been surveyed using a systematic method of measuring the depth and is based on the combination of the survey pattern and the theoretical area of detection of the survey instrumentation).

_Originally posted by @rmalyankar in https://github.com/iho-ohi/S-102-Product-Specification/issues/13#issuecomment-1781407062_

**Comment by giumas** [comment]
A very similar issue has been identified in the ONSWG by @GlenRice-NOAA: _"The one field in S-102 that concerns me is bathyCoverage. The definition seems reversed to me."_ (see https://github.com/OpenNavigationSurface/WorkingGroup/issues/5#issuecomment-2125175193)

The current note also seems to be inconsistent when to compared to the `bathyCoverage` description: 

> The attribute bathyCoverage is especially useful in side-scan surveys which are characterized by gaps in bathymetric observations with full coverage side-scan imagery (interpolated gapes between bathymetry coverage in this situation would show fullCoverage = True and bathyCoverage = False). If fullCoverage = False, bathyCoverage must also equal False, such as gaps between single beam echosounder data without correlating side-scan sonar coverage.

My feeling is that the original intent of `bathyCoverage` was not to be used as a _"flag for nodes populated by interpolation"_. Furthermore, you can have 'sparse' data (e.g., leadline) and still decide to interpolate in the S102 grid across these soundings (as it is commonly done to draw contours in nautical charts).

So I believe that we have 2 options:

- Modify the description of `bathyCoverage` to be something like _"Flag for nodes populated by a measured depth_".
- Modify the name of `bathyCoverage` to be `interpolatedCoverage` (and modifying the note accordingly).

It is also an option to do both (i.e., having both `bathyCoverage` and `interpolatedCoverage`), thus having 3 boolean attributes for 3 statuses (bathymetric coverage, full coverage and interpolated without systematic data).

A final consideration is about naming inconsistency between 'bathyCoverage' and 'fullSeafloorCoverage**Achieved**'. Given that they are using in combination, the `Achieved` should be present or absent in both names.

**Comment by giumas** [comment]
@RohdeBSH @anthonyklemm @rmalyankar, given that we already have `fullSeafloorCoverageAchieved`, then what about `bathyCoverageAchieved` ?

**Comment by giumas** [comment]
The discussion will continue in https://github.com/iho-ohi/S-102-Product-Specification/issues/115
