### ISSUE TITLE
Cancellation support clarification

### ISSUE THREAD

**Issue by skjeves** [iho-ohi/S-102-Product-Specification#81]
As a result from PT16 meeting, an action was to register the cancellation topic. 
Briefly explained, our PS needs amendment to fully implement the support for the fileless cancellation mechanism, as described in S-100 Part 17. There was concensus in PT16 to support only this mechanism, and not the file-based cancellation mechanism. 

However, there is an ongoing discussion related to an identified security breach in the fileless cancellation mechanism, namely the inability to digitally sign a fileless cancellation instruction. 
The topic is up for discussion in WENDWGs February 2024 meeting, and will be monitored to provide further feedback in this issue. Hopefully the outcome will help our PT to make a final decision and implement support for the fileless cancellation mechanism. 

Further information on the topic is available in this paper and the accompanying presentation:
[S102PT16 Cancellation support clarification.pdf](https://github.com/iho-ohi/S-102-Product-Specification/files/14107965/S102PT16.Cancellation.support.clarification.pdf)
[S-102PT16_Cancellation support clarification pres.pdf](https://github.com/iho-ohi/S-102-Product-Specification/files/14107970/S-102PT16_Cancellation.support.clarification.pres.pdf)

**Comment by rmalyankar** [comment]
S-100 Part 17 clause 17-4.4.1 says:
> Fileless cancellation may be achieved by using a dataset metadata entry with the filename and original digital signature specifying the resource to be cancelled, and with all other mandatory metadata fields also set to the same values as the original.

"all other mandatory attributes" would cover _issueDate_ too, so the dataset discovery metadata block in the cancelling CATALOG.XML would have to be the date the dataset was originally issued. Two issues arise:

1. How does the producer indicate the date the cancellation becomes effective?
2. What is the effective date of cancellation on the end-user system?

The answer to the second should be "when the cancellation is received and applied on the end-user system". Addressing the first may need an S-100 update to allow cancellation blocks to specify an issue date and time no earlier than the original.

**Comment by skjeves** [comment]
I agree with Raphael, I would expect the cancellation instruction itself to have its own issue date encoded, as that would reflect the date the cancellation becomes effective. The effective date of cancellation on the end-user system would be the date the cancellation instruction reaches the end user system. It is not possible to encode a cancellation instruction specifying a future point in time to become effective.

Another issue is the original digital signature specifying the resource to be cancelled. I cannot see how this makes the process any safer. It would still be possible for a Data Server to issue a cancellation instruction that does not originate from the data producer.

**Comment by skjeves** [comment]
Update from S-100 Test Strategy Meeting (S100TSM10): 
TSM decided on the following decision:
![image](https://github.com/iho-ohi/S-102-Product-Specification/assets/3088923/894f3db2-44b0-410c-8e61-96b889608d10)

**Comment by skjeves** [comment]
To update the S-102 Product Specification, I would suggest amend chapter 11.2.1 Dataset management as described here to avoid calling cancellation a dataset type - as a fileless cancellation is not a dataset:

11.2.1 Dataset management
Two types of dataset files may be produced and contained within an exchange set:
— New dataset: Initial. 
— New edition of a dataset: Includes new information. New editions must cover at least the same area as its predecessor. 

Cancellation. The dataset is cancelled and no longer available to be displayed or used.  
S-102 uses the fileless cancellation method described in S-100 5.2.0 Part 17 clause 17-4.4.1:
Fileless cancellation may be achieved by using a dataset metadata entry with the filename and original digital signature specifying the resource to be cancelled, and with all other mandatory metadata fields also set to the same values as the original, with the exception of the issue date which must be set to the issueDate of the fileless cancellation itself.

Another approach could be to look at S-104/S-111 chapter 8.2.4.2 which have more extensive descriptions related to metadata for cancellation (although minor updating of them is needed as well ref previous comment).

**Comment by hasel001** [comment]
I have created a [pull request](https://github.com/iho-ohi/S-102-Product-Specification/pull/96), which incorporates harmonization with an advance copy of the S-104 PS as suggested by @rmalyankar. Upon review, approval, and merge, this issue may be closed.

**Comment by hasel001** [comment]
The relevant PR has been merged, so this issue will be closed. Thanks to everyone who contributed to this solution.
