### ISSUE TITLE
Review - Abstract

### ISSUE THREAD

**Issue by RohdeBSH** [iho-ohi/S-102-Product-Specification#82]
I think abstract is not correct.
The question is how exactly this part of the document should or must be designed.
In the end, the S-102 product consists of up to two coverages.
One for the depth values and the uncertainty, and one for the metadata.
In my opinion, the metadata mentioned in the first sentence refers to the metadata stored in the attributes, not in the metadata coverage.
However, the metadata coverage is not included either.
As I mentioned before, I'm not sure how accurate this section should be. If it is too precise, it will have to be constantly adjusted. If it's not accurate enough, it doesn't reflect the facts.
What is your opinion?

_Originally posted by @RohdeBSH in https://github.com/iho-ohi/S-102-Product-Specification/pull/73#discussion_r1451942171_

**Comment by hasel001** [comment]
@RohdeBSH The alignment edits have substantially changed the abstract. Will you please either:

1. Describe any problems you see regarding the wording presently in the Developing branch

OR

2. Mark the issue as closed?

Thank you!
