### ISSUE TITLE
ExchangeSet - S100_ExchangeCatalogue - identifier

### ISSUE THREAD

**Issue by RohdeBSH** [iho-ohi/S-102-Product-Specification#87]
Hi all,

Why is the "identifier"-Tag in an S-102 ExchangeSet mandatory?
According to S-100 ed. 5.2.0 the tag is optional. 
I know of no reason why we should make life harder for ourselves here than it has to be.
And of course I don't know what to put in here or how to generate a meaningful value.

Any guidance is welcome...

https://github.com/iho-ohi/S-102-Product-Specification/blob/cffb0c33b6873d9a0ebcb61117a0e130c56d1c64/sources/3.0.0/sections/12-metadata.adoc?plain=1#L103C2-L103C3

**Comment by hasel001** [comment]
After the merge to reduce the amount of copy-paste, especially in the Metadata section, S100_ExchangeCatalogue now states that S-102 uses it without modification.

I recommend we leave this issue open. If anyone is aware of a compelling reason to make _identifier_ mandatory, please post here as soon as possible. In the absence of objection, I believe we should revert here to the S-100 (i.e., optional) status.

**Comment by RohdeBSH** [comment]
S-102PT19 decided to close this issue
